# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: brunoalmeida195@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Esse é um teste para o aprendizado de jekyll, a partir dele criarei meu blog, onde estarei 
  adicionando posts sobre algo que aprendi pela web e explicando em um post. Preciso me desafiar, chega
  de ficar se escondendo!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://www.whoisbruno.com.br" # the base hostname & protocol for your site
twitter_username: brunosheet
github_username:  brunob182

# Build settings
# kramdown = interpretador do markdown, padrão do github e muito completo :)
markdown: kramdown
# Estilo de URL https://jekyllrb.com/docs/permalinks/
# permalink: /:categories/:year/:month/:day/:title
permalink: /:title
